config/routes.rb
Rails.application.routes.draw do
  get 'favorites/index'
  get 'favorites/new'
  get 'favorites/show'
  get 'favorites/edit'
  devise_for :users
  resources :diaries
 

  authenticated :user do
	  root "diaries#index", as: "authenticated_root" 
  end
  root 'home#index'

delete "diaries/:id", to: "diaries#destroy"



end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diarie.rb
class Diarie < ApplicationRecord
    // 
    belongs_to :user
    has_many :favorites
  has_many :users, through: :favorites
  has_one_attached :image


  validates :title, presence: true 

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :diarie
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        has_many :diaries, class_name: 'Diarie'
        has_many :favorites, class_name: 'Favorite'
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def favorite_text
return @favorite_exists ? "UnFavorite" : "Favorite"
    end 
    #helper method - if the favorite is exist remove the favorite if it exists 
    helper_method :favorite_text 

    
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController

        before_action :find_diarie, only: [:show, :edit, :update, :destroy]
        before_action :authenticate_user!    
        def index
            @diaries = Diarie.where(user_id: current_user) #to show only diaries belongs to the current users 
        end
    
        def show
            @diarie = Diarie.find(params[:id])
            @favorite_exists = Favorite.where(diarie: @diarie, user: current_user)== [] ? false : true 
        end
    
        def new
            @diarie = current_user.diaries.build 
        end
    
        def create
            @diarie = current_user.diaries.build(diarie_params)
    
            if @diarie.save
                redirect_to @diarie
            else
                render 'new'
            end
        end
    
        def edit
            @diarie = Diarie.find(params[:id])

        end
    
        def update
            if @diarie.update(diarie_params)
                redirect_to @diarie
            else
                render 'edit'
            end
        end
    
        def destroy
            @diarie.destroy
            redirect_to diaries_path
        end
    
        def bootstrap

        end 
      
        private
    
        def find_diarie
            @diarie = Diarie.find(params[:id])
        end
    
        def diarie_params
            params.require(:diarie).permit(:title, :content, :media)
        end
    end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

def edit
favorite = Favorite.where(diarie: Diarie.find(params[:diarie]), user: current_user) 
if favorite==[]
#create the favorite 
Favorite.create(diarie: Diarie.find(params[:diarie]), user: current_user )
@favorite_exists = true 
else 
  #delete the favorite 
favorite.destroy_all
@favorite_exists = false 
end 
respond_to do |format|
  format.html {}
  format.js {}
    end 
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/diaries/_form.html.erb
<%= form_for @diarie do |f| %>
<div class="jumbotron main-view">
  <div class="input-field col s6">
    <%= f.label :title, 'Title'%>
    <%= f.text_field :title%>
  </div>
  <div class="input-field col s6">
    <%= f.label :content, 'Content' %>
    <%= f.text_area :content, size:"50x10"%>
  
  </div>
  <div class="input-field col s6">
    <%= f.label :media, 'Media' %>
    <%= f.text_field :media %>
  </div>
  <div class= "field">
  <%= f.label :image %>
  <%=  f.file_field :image %>
  </div >


    <div class="form-group">
  <%= f.submit "Submit", class:"btn btn-dark" %>
  </div>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

app/views/diaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class ="all">All the diaries </h1>

 <%= link_to "Your Favorite Diaries" , favorites_show_path, class:"btn btn-outline-secondary", id:"new" %>

<div class = "empty">  ...  </div>
<div class="card-columns">

 <% @diaries.each do |diarie| %>
     <div class="card main-view">
       <div class="card-body">
          <h2 class="card-title">
         <%= link_to diarie.title, diarie, class:"text-dark" %> 
           </h2>
           <div class="card-footer">
           <%= time_ago_in_words(diarie.created_at)%> 
           </div> 
        
    </div>
   
     </div>


 <% end %>
 </div> 

<div class = "empty">  ...  </div>

 <%= link_to "New Diary", new_diary_path, class:"btn btn-outline-secondary", id:"new" %>

app/views/diaries/new.html.erb
<h2> New diary </h2>
<%= render 'form' %>


 <%= link_to 'Back', diaries_path , class:"btn btn-outline-secondary"%>

app/views/diaries/show.html.erb
<div class="diary">

<h1><%= @diarie.title %></h1>

 <p class= "content"><%= @diarie.content %></p>
 <h3><%= @diarie.media %></h3>
 <div style = "width:200px; height:auto">
 <% link_to image_tag(@diarie.media, style:'width:100%'), diaries_path %>
 </div >


 <div class="btn-group" role="group">


<%= link_to "Edit", edit_diary_path(@diarie), class:"btn btn-outline-dark btn-sm" %>
 <%= link_to 'Delete', @diarie, method: :delete, data: { confirm: "Are you sure you want to delete it ?"} , class:"btn btn-outline-dark btn-sm"%> 
 <%= link_to 'Back', diaries_path , class:"btn btn-outline-dark btn-sm"%>
<%= link_to favorite_text , favorites_edit_path(diarie: @diarie), id:'favorite_link', remote: true , class:"btn btn-outline-dark btn-sm"%>
</div>
</div>

app/views/favorites/edit.js.erb
$('#favorite_link').text("<%= favorite_text%>"); 

app/views/favorites/index.html.erb
<h1>Favorites#index</h1>
<p>Find me in app/views/favorites/index.html.erb</p>

app/views/favorites/new.html.erb
<h1>Favorites#new</h1>
<p>Find me in app/views/favorites/new.html.erb</p>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<h1> <center> Your Favorite diaries </center> </h1>
     <div class="card-columns">
      <div class="card-body">
         <h2 class="card-title">
<% current_user.favorites.each do |favorite| %>

<div class="card main-view"> 
<%= link_to favorite.diarie.title, favorite.diarie,class:"text-dark" %>
</h2>

</div>
</div>
<%end%>

<%= link_to "back" , diaries_path, class:"btn btn-outline-secondary", id:"new" %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>




<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" >
    <div class="carousel-item active" >
      <%= image_tag("diary-4.jpg", :alt => "first slide",class:"d-block w-100") %>
    </div>
    <div class="carousel-item">
       <%= image_tag("diray-7.jpeg", :alt => "Second slide",class:"d-block w-100") %>
    </div>
    <div class="carousel-item">
         <%= image_tag("diary-6.jpg", :alt => "Third slide", class:"d-block w-100")%>
    </div>
   
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  </div>
</div>
  <div class="footer">
  <p>All Rights Reserved © 2019 </p>
</div>

app/views/layouts/_nav.html.erb
    <% if user_signed_in? %>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class = "container">
  <%= image_tag("TOP.png", :alt => "logo", class:"navbar-brand",size:"150x90")%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
   <li class="nav-item">
   <div class="btn btn-outline-secondary">
 <%= link_to 'My Account', edit_user_registration_path , class:"nav-link" %>
 </div>
   </li>

      <li class="nav-item">
      <div class="btn btn-outline-secondary">
<%= link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link" %>
       </div>
      </li>
   
    </ul>
  </div>
  </div>
</nav>


<%else%>
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= image_tag("TOP.png", :alt => "logo", class:"navbar-brand", size:"150x90")%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
      <div class="btn btn-outline-secondary">
 <%= link_to "log in", new_user_session_path, class:"nav-link" %>
 </div>
      </li>

      <li class="nav-item">
      <div class="btn btn-outline-secondary">
<%= link_to "sign up", new_user_registration_path, class:"nav-link" %>
  </div>
      </li>
   
    </ul>
  </div>
</nav>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
         <%= render 'layouts/nav' %> 
       <p class="alert-heading"><%= alert %></p>
  <body>
  
    <%= yield %>
  

  </body>

</html>